edited Readme
HAPIprotocol/hapi-near-connector pull request #3
Opened 2023-03-22 09:54 UTC by Sergei2404

2023-03-22 10:37 UTC, ars9 requested changes

2023-03-22 10:37 UTC, ars9 commented on README.md
> +[HAPI] is a one-of-a-kind decentralized security protocol that prevents and interrupts any potential malicious activity within the blockchain space. HAPI works by leveraging both external and off-cha
Please replace all "HAPI" occurences with "HAPI Protocol" to avoid ambiguity.

2023-03-22 10:37 UTC, ars9 commented on README.md
> +[HAPI] is a one-of-a-kind decentralized security protocol that prevents and interrupts any potential malicious activity within the blockchain space. HAPI works by leveraging both external and off-cha
Note: letter capitalization is important.

2023-03-22 10:37 UTC, ars9 commented on README.md
> +It is a proxy [contract](https://github.com/HAPIprotocol/near-proxy-contract) used for reporting and receiving data from [HAPI] protocol main contract on the NEAR blockchain.
Let's replace "reporting and receiving data" with "replicating data".

2023-03-22 10:37 UTC, ars9 commented on README.md
> +This crate helps implement the use of the [HAPI] in your smart contract on the NEAR blockchain. You can use it to make request data from the proxy contract, and subsequent processing this data.
"This crate helps to implement HAPI Protocol in your smart contract..." would sound a bit cleaner.

2023-03-22 10:37 UTC, ars9 commented on README.md
> +This crate helps implement the use of the [HAPI] in your smart contract on the NEAR blockchain. You can use it to make request data from the proxy contract, and subsequent processing this data.
"to make request" - here "make" isn't needed.

2023-03-22 10:37 UTC, ars9 commented on README.md
> +2. Add use hapi in your lib.rs file
What does "use hapi" mean? Shouldn't it be `use hapi_near_connector`?

2023-03-22 10:37 UTC, ars9 commented on README.md
> +5. Add cross-contract call to the method on which we need to use hapi
"we need to use the protocol" would look better.

2023-03-22 10:37 UTC, ars9 commented on README.md
> +6. Create a trait with a callback to handle response from HAPI near proxy.
Please use a proper capitalization of "NEAR".

2023-03-22 10:37 UTC, ars9 commented on README.md
> +It is short description of steps you need to do to implement hapi in you contract. For detailed information go to [example](#example-of-integration-into-the-ft-contract)
"steps you need to implement HAPI Protocol"

2023-03-22 10:37 UTC, ars9 commented on README.md
> +>If the risk level was not set for some categories, then the risk level for the category **All** is used.
Can you describe the configuration for a case when the consumer doesn't need to differentiate between categories at all?

2023-03-22 10:37 UTC, ars9 commented on README.md
> +![img1](img/img1.png)
This shouldn't be an image.

2023-03-22 10:37 UTC, ars9 commented on README.md
> +* *ext_aml* - it's hapi's trait.
"it's the connector's trait"

2023-03-22 10:37 UTC, ars9 commented on README.md
> +5. Add cross-contract call to the method on which we need to use hapi.
"to use the connector".

2023-03-22 10:37 UTC, ars9 commented on README.md
> +    ext_aml::ext(self.aml.get_account())
Can you please add a short comment that explains what happens in this block depending on the protocol data?

2023-03-22 10:37 UTC, ars9 commented on README.md
> +After that, your contract can already work with Hapi.
"work with HAPI Protocol"

2023-03-22 10:37 UTC, ars9 commented on README.md
> +
Let's add a suggestion to configure categories during a migration if that's something the contract owner doesn't plan to do often.

2023-03-22 10:37 UTC, ars9 commented on README.md
> +Also you can integrate HAPI without crate, you can find [example on Jumbo exchange](https://github.com/jumbo-exchange/contracts#hapi-protocol-integration).
"integrate HAPI Protocol without this crate"

2023-03-22 14:09 UTC, Sergei2404 commented on README.md
> +>If the risk level was not set for some categories, then the risk level for the category **All** is used.
For example, when the user agrees that all categories in our list of categories are unacceptable for him.

2023-03-23 09:15 UTC, ars9 requested changes

2023-03-23 09:15 UTC, ars9 commented on README.md
> +It is a proxy [contract](https://github.com/HAPIprotocol/near-proxy-contract) used for replicating data from [HAPI Protocol] protocol main contract on the NEAR blockchain.
Please remove the duplicate "protocol".

2023-03-23 09:15 UTC, ars9 commented on README.md
> +After that, your contract can already work with HAPI Protocol.
"your contract is ready to work with"

2023-03-23 09:15 UTC, ars9 commented on README.md
> +        // if you doesn't plan to add categories often you can do it right away
"if you don't plan to modify categories"

2023-03-23 09:16 UTC, ars9 commented on README.md
> +>If the risk level was not set for some categories, then the risk level for the category **All** is used.
I mean add it to this note :)

2023-03-23 09:32 UTC, ars9 approved these changes
LGTM

2023-03-23 13:46 UTC, merged